# Generated by Django 5.1.5 on 2025-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_carrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con descuento'),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
